# Generated by Django 4.2 on 2025-04-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Инвентаризация", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название отдела"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Инвентаризация.department",
                        verbose_name="Название цеха",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отдел",
                "db_table": "Инвентаризация_section",
            },
        ),
        migrations.AddField(
            model_name="compyuter",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Инвентаризация.section",
                verbose_name="Отдел",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompyuter",
            name="section",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="Инвентаризация.section",
                verbose_name="Отдел",
            ),
        ),
    ]
