# Generated by Django 4.2 on 2025-04-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Инвентаризация.department', verbose_name='Название цеха'),
            preserve_default=False,
        ),
    ]
